server:
  port: "8080"
  mode: "debug"

database:
  host: "localhost"
  port: "3306"
  username: "root"
  password: "123456"
  dbname: "memberlink_lite"
  charset: "utf8mb4"
  parseTime: true
  loc: "Local"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

jwt:
  secret: "memberlink-lite-secret-key-change-in-production"
  issuer: "memberlink-lite"
  access_token_ttl: 24    # hours
  refresh_token_ttl: 168  # hours (7 days)

log:
  level: "info"
  format: "json"

# 存储配置
storage:
  type: "local"  # 存储类型: local, aliyun, tencent
  
  # 本地存储配置
  local:
    base_path: "./uploads"
    base_url: "http://localhost:8080/uploads/"
  
  # 阿里云OSS配置（需要时启用）
  aliyun:
    endpoint: ""
    access_key_id: ""
    access_key_secret: ""
    bucket_name: ""
    region: ""
    use_https: true
    custom_domain: ""
  
  # 腾讯云COS配置（需要时启用）
  tencent:
    secret_id: ""
    secret_key: ""
    region: ""
    bucket_name: ""
    app_id: ""
    use_https: true
    custom_domain: ""

# SSO配置
sso:
  enabled: false  # 全局SSO开关
  
  # 微信SSO配置
  wechat:
    enabled: false
    app_id: ""
    app_secret: ""
    redirect_uri: "http://localhost:8080/api/v1/auth/sso/wechat/callback"
    # 多租户配置：按租户覆盖上述配置
    tenants: {}
    
    # 多租户配置示例（可选）
    # tenants:
    #   tenant1:
    #     enabled: true
    #     app_id: "wx1234567890abcdef"
    #     app_secret: "your_tenant1_app_secret"
    #     redirect_uri: "http://tenant1.example.com/auth/callback"
    #   tenant2:
    #     enabled: true
    #     app_id: "wx0987654321fedcba"
    #     app_secret: "your_tenant2_app_secret"
    #     redirect_uri: "http://tenant2.example.com/auth/callback"

# 多租户配置
tenant:
  enabled: false  # 多租户功能开关
  
  # 默认租户配置
  default:
    name: "Default Tenant"
    domain: "localhost"
    enabled: true
    settings:
      max_users: 1000
      storage_limit: "10GB"
  
  # 其他租户配置示例（可选）
  # tenants:
  #   tenant1:
  #     name: "Tenant 1"
  #     domain: "tenant1.example.com"
  #     enabled: true
  #     settings:
  #       max_users: 500
  #       storage_limit: "5GB"
  #       custom_theme: "blue"
  #   tenant2:
  #     name: "Tenant 2"
  #     domain: "tenant2.example.com"
  #     enabled: true
  #     settings:
  #       max_users: 200
  #       storage_limit: "2GB"
  #       custom_theme: "green"