# 服务器配置
# 环境变量: SERVER_PORT, SERVER_MODE
server:
  port: "8080"
  mode: "debug"

# 数据库配置
# 环境变量: DATABASE_HOST, DATABASE_PORT, DATABASE_USERNAME, DATABASE_PASSWORD, DATABASE_DBNAME
database:
  host: "localhost"
  port: "3306"
  username: "root"
  password: "123456"
  dbname: "memberlink_lite"
  charset: "utf8mb4"
  parseTime: true
  loc: "Local"
  # 连接池配置
  # 环境变量: DATABASE_MAX_IDLE_CONNS, DATABASE_MAX_OPEN_CONNS, DATABASE_CONN_MAX_LIFETIME_HOURS
  max_idle_conns: 10              # 最大空闲连接数
  max_open_conns: 50             # 最大打开连接数
  conn_max_lifetime_hours: 2      # 连接最大生存时间（小时）

# Redis配置
# 环境变量: REDIS_HOST, REDIS_PORT, REDIS_PASSWORD, REDIS_DB
redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

# JWT配置
# 环境变量: JWT_SECRET, JWT_ISSUER, JWT_ACCESS_TOKEN_TTL, JWT_REFRESH_TOKEN_TTL
jwt:
  secret: "memberlink-lite-secret-key-change-in-production"
  issuer: "memberlink-lite"
  access_token_ttl: 24    # hours
  refresh_token_ttl: 168  # hours (7 days)

# 日志配置
# 环境变量: LOG_LEVEL, LOG_FORMAT
log:
  level: "info"
  format: "json"

# 存储配置
storage:
  type: "local"  # 存储类型: local, aliyun, tencent
  
  # 本地存储配置
  local:
    base_path: "./uploads"
    base_url: "http://localhost:8080/uploads/"
  
  # 阿里云OSS配置（需要时启用）
  aliyun:
    endpoint: ""
    access_key_id: ""
    access_key_secret: ""
    bucket_name: ""
    region: ""
    use_https: true
    custom_domain: ""
  
  # 腾讯云COS配置（需要时启用）
  tencent:
    secret_id: ""
    secret_key: ""
    region: ""
    bucket_name: ""
    app_id: ""
    use_https: true
    custom_domain: ""

# 微信小程序登录配置
wechat:
  enabled: true           # 微信小程序登录开关
  app_id: "wx4e2a37f5eca8d18b"              # 微信小程序AppID
  app_secret: "5243c5e34f58a9f0b4d1aae444c4473b"          # 微信小程序AppSecret
  
  # 多租户微信配置示例（仅在tenant.enabled=true时生效）
  # tenants:
  #   company1:
  #     enabled: true
  #     app_id: "wx1234567890abcdef"
  #     app_secret: "your_company1_app_secret"
  #   company2:
  #     enabled: true
  #     app_id: "wx0987654321fedcba"
  #     app_secret: "your_company2_app_secret"

# 多租户配置（简化版）
tenant:
  enabled: false  # 多租户功能开关，false=单租户模式，true=多租户模式
  header_name: "X-Tenant-ID"  # 自定义Header名称
  query_name: "tenant_id"     # 自定义Query参数名称
  
  # 租户配置示例（仅在enabled=true时生效）
  # tenants:
  #   tenant1:
  #     name: "租户1"
  #     domain: "tenant1.example.com"
  #     enabled: true
  #   tenant2:
  #     name: "租户2" 
  #     domain: "tenant2.example.com"
  #     enabled: true

# CORS配置
# 环境变量: CORS_ALLOWED_ORIGINS, CORS_ALLOW_CREDENTIALS, CORS_MAX_AGE
cors:
  # 允许的来源域名，逗号分隔，生产环境请配置具体域名
  allowed_origins: "http://localhost:3000,http://localhost:8080"
  allow_credentials: true
  max_age: "12h"