# 服务器配置
# 环境变量: SERVER_PORT, SERVER_MODE
server:
  port: "8080"
  mode: "debug"

# 数据库配置
# 环境变量: DATABASE_HOST, DATABASE_PORT, DATABASE_USERNAME, DATABASE_PASSWORD, DATABASE_DBNAME
database:
  host: "localhost"
  port: "3306"
  username: "root"
  password: "123456"
  dbname: "memberlink_lite"
  charset: "utf8mb4"
  parseTime: true
  loc: "Local"
  # 连接池配置
  # 环境变量: DATABASE_MAX_IDLE_CONNS, DATABASE_MAX_OPEN_CONNS, DATABASE_CONN_MAX_LIFETIME_HOURS
  max_idle_conns: 10              # 最大空闲连接数
  max_open_conns: 100             # 最大打开连接数
  conn_max_lifetime_hours: 1      # 连接最大生存时间（小时）

# Redis配置
# 环境变量: REDIS_HOST, REDIS_PORT, REDIS_PASSWORD, REDIS_DB
redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

# JWT配置
# 环境变量: JWT_SECRET, JWT_ISSUER, JWT_ACCESS_TOKEN_TTL, JWT_REFRESH_TOKEN_TTL
jwt:
  secret: "memberlink-lite-secret-key-change-in-production"
  issuer: "memberlink-lite"
  access_token_ttl: 24    # hours
  refresh_token_ttl: 168  # hours (7 days)

# 日志配置
# 环境变量: LOG_LEVEL, LOG_FORMAT
log:
  level: "info"
  format: "json"

# 存储配置
storage:
  type: "local"  # 存储类型: local, aliyun, tencent
  
  # 本地存储配置
  local:
    base_path: "./uploads"
    base_url: "http://localhost:8080/uploads/"
  
  # 阿里云OSS配置（需要时启用）
  aliyun:
    endpoint: ""
    access_key_id: ""
    access_key_secret: ""
    bucket_name: ""
    region: ""
    use_https: true
    custom_domain: ""
  
  # 腾讯云COS配置（需要时启用）
  tencent:
    secret_id: ""
    secret_key: ""
    region: ""
    bucket_name: ""
    app_id: ""
    use_https: true
    custom_domain: ""

# SSO配置
sso:
  enabled: false  # 全局SSO开关
  
  # 微信SSO配置
  wechat:
    enabled: false
    app_id: ""
    app_secret: ""
    redirect_uri: "http://localhost:8080/api/v1/auth/sso/wechat/callback"
    # 多租户配置：按租户覆盖上述配置
    tenants: {}
    
    # 多租户配置示例（可选）
    # tenants:
    #   tenant1:
    #     enabled: true
    #     app_id: "wx1234567890abcdef"
    #     app_secret: "your_tenant1_app_secret"
    #     redirect_uri: "http://tenant1.example.com/auth/callback"
    #   tenant2:
    #     enabled: true
    #     app_id: "wx0987654321fedcba"
    #     app_secret: "your_tenant2_app_secret"
    #     redirect_uri: "http://tenant2.example.com/auth/callback"

# 多租户配置
tenant:
  enabled: false  # 多租户功能开关
  
  # 默认租户配置
  default:
    name: "Default Tenant"
    domain: "localhost"
    enabled: true
    settings:
      max_users: 1000
      storage_limit: "10GB"
  
  # 其他租户配置示例（可选）
  # tenants:
  #   tenant1:
  #     name: "Tenant 1"
  #     domain: "tenant1.example.com"
  #     enabled: true
  #     settings:
  #       max_users: 500
  #       storage_limit: "5GB"
  #       custom_theme: "blue"
  #   tenant2:
  #     name: "Tenant 2"
  #     domain: "tenant2.example.com"
  #     enabled: true
  #     settings:
  #       max_users: 200
  #       storage_limit: "2GB"
  #       custom_theme: "green"

# CORS配置
# 环境变量: CORS_ALLOWED_ORIGINS, CORS_ALLOW_CREDENTIALS, CORS_MAX_AGE
cors:
  # 允许的来源域名，逗号分隔，生产环境请配置具体域名
  allowed_origins: "http://localhost:3000,http://localhost:8080"
  allow_credentials: true
  max_age: "12h"